model_list:
  - model_name: fireworks-llama-v3p1-405b-instruct
    litellm_params:
      model: fireworks_ai/accounts/fireworks/models/llama-v3p1-405b-instruct
      api_key: os.environ/API_KEY
  - model_name: fireworks-llama-v3p1-70b-instruct
    litellm_params:
      model: fireworks_ai/accounts/fireworks/models/llama-v3p1-70b-instruct
      api_key: os.environ/API_KEY
